# Generated by Django 5.0.6 on 2025-11-07 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('Movie', 'movie'), ('Shows', 'shows')], max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Budget', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Duration', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relaton', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
